AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  number-swap

  Sample SAM Template for number-swap

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:
  NumberSwapFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: number_swap/
      Handler: app.lambda_handler
      Runtime: python3.8
      Architectures:
        - x86_64
      Events:
        NumberSwap:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /hello
            Method: get
            RequestParameters:
              - method.request.querystring.numbers:
                 Required: true


Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  NumberSwapApi:
    Description: "API Gateway endpoint URL for Prod stage for number swap function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  NumberSwapFunction:
    Description: "number swap Lambda Function ARN"
    Value: !GetAtt NumberSwapFunction.Arn
  NumberSwapFunctionIamRole:
    Description: "Implicit IAM Role created for number swap function"
    Value: !GetAtt NumberSwapFunctionRole.Arn
